---
- name: Apply role docker
  hosts: manager

  vars:
    docker_enforce_restart: true

  collections:
    - osism.services

  roles:
    - role: docker

- name: Apply role docker-compose
  hosts: manager

  collections:
    - osism.commons

  roles:
    - role: docker_compose
